import { PickList } from "./WarehousePickingView"
import { PurchaseOrder } from "./WarehouseReceivingView"
import { InventoryItem } from "./WarehouseInventoryView"
import { DispatchOrder } from "./WarehouseDispatchView"
import { WarehouseActivityData } from "./WarehouseAuditLedgerView"

export const FALLBACK_PICK_LISTS: PickList[] = [
  {
    id: "pk-demo-1021",
    pickNumber: "PK-1021",
    orderId: "so-demo-1082",
    orderNumber: "SO-1082",
    customerName: "Bella Italia Pizzeria (Surry Hills)",
    assignedTo: "Tony Marchetti",
    assignedToId: "wh-user-1",
    status: "in_progress",
    priority: "high",
    warehouseName: "Sydney Central Logistics Hub & Coldstore",
    createdAt: new Date().toISOString(),
    progress: 45,
    items: [
      {
        id: "pki-1",
        productId: "prod-1",
        productName: "Artisan 12\" Sourdough Pizza Crusts (24pk)",
        sku: "PZ-CRUST-12",
        location: "COLD-ROOM-01",
        requiredQty: 10,
        pickedQty: 5,
        status: "pending",
        batchCode: "LOT-20260822",
      },
      {
        id: "pki-2",
        productId: "prod-2",
        productName: "Fior di Latte Shredded Mozzarella (5kg)",
        sku: "CH-MOZZ-5KG",
        location: "COLD-ROOM-01",
        requiredQty: 4,
        pickedQty: 4,
        status: "picked",
        batchCode: "LOT-20260822",
      },
      {
        id: "pki-3",
        productId: "prod-3",
        productName: "San Marzano D.O.P. Crushed Tomatoes (10kg BIB)",
        sku: "SAUCE-SAN-10KG",
        location: "AISLE-A-01",
        requiredQty: 3,
        pickedQty: 0,
        status: "pending",
      },
    ],
  },
  {
    id: "pk-demo-1022",
    pickNumber: "PK-1022",
    orderId: "so-demo-1089",
    orderNumber: "SO-1089",
    customerName: "Criniti's Darling Harbour",
    assignedTo: "Tony Marchetti",
    assignedToId: "wh-user-1",
    status: "pending",
    priority: "normal",
    warehouseName: "Sydney Central Logistics Hub & Coldstore",
    createdAt: new Date().toISOString(),
    progress: 0,
    items: [
      {
        id: "pki-4",
        productId: "prod-4",
        productName: "Snap-Frozen Neapolitan Dough Balls 250g (60pk)",
        sku: "PZ-DOUGH-250",
        location: "COLD-ROOM-02",
        requiredQty: 12,
        pickedQty: 0,
        status: "pending",
      },
      {
        id: "pki-5",
        productId: "prod-5",
        productName: "Prosciutto di Parma 24M Sliced (1kg Vac-Pack)",
        sku: "MT-PROSC-1KG",
        location: "COLD-ROOM-02",
        requiredQty: 8,
        pickedQty: 0,
        status: "pending",
      },
    ],
  },
]

export const FALLBACK_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "po-demo-104",
    poNumber: "PO-2026-104",
    supplier: {
      id: "supp-1",
      name: "Primo Smallgoods & Cheeses",
      email: "orders@primo.com.au",
      phone: "02 9794 8888",
    },
    orderDate: new Date().toISOString(),
    expectedDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    totalAmount: 4250.0,
    status: "confirmed",
    items: [
      {
        id: "poi-1",
        productId: "prod-2",
        product: {
          id: "prod-2",
          name: "Fior di Latte Shredded Mozzarella (5kg Chilled)",
          sku: "CH-MOZZ-5KG",
          baseUnit: "bag",
        },
        quantity: 50,
        receivedQty: 0,
        unitCost: 42.0,
        totalCost: 2100.0,
      },
      {
        id: "poi-2",
        productId: "prod-5",
        product: {
          id: "prod-5",
          name: "Prosciutto di Parma 24M Sliced (1kg Vac-Pack)",
          sku: "MT-PROSC-1KG",
          baseUnit: "pack",
        },
        quantity: 25,
        receivedQty: 0,
        unitCost: 34.0,
        totalCost: 850.0,
      },
      {
        id: "poi-3",
        productId: "prod-8",
        product: {
          id: "prod-8",
          name: "Gorgonzola Dolce D.O.P. (1.5kg Wheel)",
          sku: "CH-GORG-1.5KG",
          baseUnit: "wheel",
        },
        quantity: 20,
        receivedQty: 0,
        unitCost: 29.0,
        totalCost: 580.0,
      },
    ],
  },
  {
    id: "po-demo-105",
    poNumber: "PO-2026-105",
    supplier: {
      id: "supp-2",
      name: "Mutti Italian Tomato Imports",
      email: "supply@mutti.com.au",
      phone: "02 8821 5500",
    },
    orderDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    expectedDate: new Date().toISOString(),
    totalAmount: 3080.0,
    status: "partial",
    items: [
      {
        id: "poi-4",
        productId: "prod-3",
        product: {
          id: "prod-3",
          name: "San Marzano D.O.P. Crushed Tomatoes (10kg BIB)",
          sku: "SAUCE-SAN-10KG",
          baseUnit: "box",
        },
        quantity: 80,
        receivedQty: 40,
        unitCost: 22.0,
        totalCost: 1760.0,
      },
      {
        id: "poi-5",
        productId: "prod-6",
        product: {
          id: "prod-6",
          name: "Cold-Pressed Extra Virgin Olive Oil (15L Drum)",
          sku: "OIL-EVOO-15L",
          baseUnit: "drum",
        },
        quantity: 15,
        receivedQty: 10,
        unitCost: 85.0,
        totalCost: 1275.0,
      },
    ],
  },
]

export const FALLBACK_INVENTORY: InventoryItem[] = [
  {
    id: "inv-1",
    productId: "prod-1",
    warehouseId: "wh-1",
    quantity: 180,
    allocated: 15,
    reorderLevel: 25,
    location: "COLD-ROOM-01",
    isLowStock: false,
    product: {
      id: "prod-1",
      name: "Artisan 12\" Sourdough Pizza Crusts (24pk)",
      sku: "PZ-CRUST-12",
      baseUnit: "carton",
      category: { name: "Pizza Bases" },
    },
    warehouse: { id: "wh-1", name: "Sydney Logistics Hub" },
  },
  {
    id: "inv-2",
    productId: "prod-2",
    warehouseId: "wh-1",
    quantity: 95,
    allocated: 10,
    reorderLevel: 20,
    location: "COLD-ROOM-01",
    isLowStock: false,
    product: {
      id: "prod-2",
      name: "Fior di Latte Shredded Mozzarella (5kg Chilled)",
      sku: "CH-MOZZ-5KG",
      baseUnit: "bag",
      category: { name: "Dairy & Cheese" },
    },
    warehouse: { id: "wh-1", name: "Sydney Logistics Hub" },
  },
  {
    id: "inv-3",
    productId: "prod-3",
    warehouseId: "wh-1",
    quantity: 310,
    allocated: 28,
    reorderLevel: 50,
    location: "AISLE-A-01",
    isLowStock: false,
    product: {
      id: "prod-3",
      name: "San Marzano D.O.P. Crushed Tomatoes (10kg BIB)",
      sku: "SAUCE-SAN-10KG",
      baseUnit: "box",
      category: { name: "Sauces & Pantry" },
    },
    warehouse: { id: "wh-1", name: "Sydney Logistics Hub" },
  },
  {
    id: "inv-4",
    productId: "prod-4",
    warehouseId: "wh-1",
    quantity: 240,
    allocated: 18,
    reorderLevel: 40,
    location: "COLD-ROOM-02",
    isLowStock: false,
    product: {
      id: "prod-4",
      name: "Snap-Frozen Neapolitan Dough Balls 250g (60pk)",
      sku: "PZ-DOUGH-250",
      baseUnit: "carton",
      category: { name: "Frozen Dough" },
    },
    warehouse: { id: "wh-1", name: "Sydney Logistics Hub" },
  },
  {
    id: "inv-5",
    productId: "prod-5",
    warehouseId: "wh-1",
    quantity: 65,
    allocated: 8,
    reorderLevel: 15,
    location: "COLD-ROOM-02",
    isLowStock: false,
    product: {
      id: "prod-5",
      name: "Prosciutto di Parma 24M Sliced (1kg Vac-Pack)",
      sku: "MT-PROSC-1KG",
      baseUnit: "pack",
      category: { name: "Smallgoods" },
    },
    warehouse: { id: "wh-1", name: "Sydney Logistics Hub" },
  },
]

export const FALLBACK_DISPATCH_ORDERS: DispatchOrder[] = [
  {
    id: "so-demo-1094",
    orderNumber: "SO-1094",
    customerName: "Fratelli Fresh Sydney CBD",
    deliveryAddress: "11 Bridge Street, Sydney, NSW, 2000",
    status: "packed",
    itemsCount: 2,
    totalCartons: 14,
    totalWeight: 68.5,
    carrierName: "StarTrack Express",
    consignmentNumber: "ST-8899201",
    assignedDriverName: "Sam Nguyen",
    routeNumber: "RUN-20260823-01",
    requiredDate: new Date().toISOString(),
  },
  {
    id: "so-demo-1098",
    orderNumber: "SO-1098",
    customerName: "Totti's Bondi Beach",
    deliveryAddress: "283 Bondi Road, Bondi, NSW, 2026",
    status: "packed",
    itemsCount: 2,
    totalCartons: 55,
    totalWeight: 680.0,
    carrierName: "Mainfreight Linehaul",
    consignmentNumber: "MF-4920194",
    assignedDriverName: "3PL Freight Linehaul",
    routeNumber: "PALLET-LH-04",
    requiredDate: new Date().toISOString(),
  },
]

export const FALLBACK_ACTIVITY: WarehouseActivityData = {
  summary: {
    todayReceivedUnits: 40,
    todayDispatchedCartons: 14,
    todayDispatchedWeight: 68.5,
    totalReceivedRecords: 3,
    totalDispatchedRecords: 4,
    totalMovementsCount: 18,
  },
  receivedGoods: [
    {
      id: "rec-1",
      poId: "po-105",
      poNumber: "PO-2026-105",
      supplierName: "Mutti Italian Tomato Imports",
      productId: "prod-3",
      productName: "San Marzano D.O.P. Crushed Tomatoes (10kg BIB)",
      sku: "SAUCE-SAN-10KG",
      orderedQty: 80,
      receivedQty: 40,
      unitCost: 22.0,
      totalCost: 880.0,
      receivedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      status: "partial",
    },
    {
      id: "rec-2",
      poId: "po-104",
      poNumber: "PO-2026-104",
      supplierName: "Primo Smallgoods & Cheeses",
      productId: "prod-2",
      productName: "Fior di Latte Shredded Mozzarella (5kg)",
      sku: "CH-MOZZ-5KG",
      orderedQty: 50,
      receivedQty: 50,
      unitCost: 42.0,
      totalCost: 2100.0,
      receivedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      status: "received",
    },
  ],
  dispatchedGoods: [
    {
      id: "disp-1",
      orderNumber: "SO-1094",
      customerName: "Fratelli Fresh Sydney CBD",
      customerAddress: "11 Bridge Street, Sydney NSW 2000",
      status: "packed",
      dispatchedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      requiredDate: new Date().toISOString(),
      totalCartons: 14,
      totalWeight: 68.5,
      carrierName: "StarTrack Express",
      consignmentNumber: "ST-8899201",
      items: [
        { id: "di-1", productId: "prod-1", productName: "Artisan 12\" Sourdough Pizza Crusts (24pk)", sku: "PZ-CRUST-12", quantity: 8, pickedQty: 8, unitPrice: 48.0, totalPrice: 384.0 },
        { id: "di-2", productId: "prod-2", productName: "Fior di Latte Mozzarella (5kg)", sku: "CH-MOZZ-5KG", quantity: 6, pickedQty: 6, unitPrice: 65.0, totalPrice: 390.0 },
      ],
    },
  ],
  movementLedger: [
    {
      id: "mov-1",
      productId: "prod-1",
      productName: "Artisan 12\" Sourdough Pizza Crusts (24pk)",
      sku: "PZ-CRUST-12",
      warehouseName: "Sydney Logistics Hub",
      type: "out",
      quantity: 8,
      reason: "Picked for SO-1094",
      reference: "SO-1094",
      referenceType: "sales_order",
      userName: "Tony Marchetti",
      createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    },
    {
      id: "mov-2",
      productId: "prod-3",
      productName: "San Marzano D.O.P. Crushed Tomatoes (10kg)",
      sku: "SAUCE-SAN-10KG",
      warehouseName: "Sydney Logistics Hub",
      type: "in",
      quantity: 40,
      reason: "Inbound PO-2026-105 Dock Check-in",
      reference: "PO-2026-105",
      referenceType: "purchase_order",
      userName: "Tony Marchetti",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
}
